<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductPOS\Block\Button;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Button $block */
$product = $block->getProduct();
?>

<script>
    'use strict';

    function initNotSaleableButtonComponent() {
        return {
            moveButton() {
                var targetNode = document.querySelector(".flex.mt-4.ml-auto.sm\\:mt-0");
                if (targetNode) {
                    for (var child of this.$root.children) {
                        targetNode.append(child);
                    }
                }
            }
        }
    }
</script>

<?php if (! $product->isSaleable() && $block->isNotSaleable() && $block->showButton()) :?>
    <?php $buttonText = $block->getButtonText(); ?>
    <div class="catalog-product-pos-button-box"
         x-data="initNotSaleableButtonComponent()"
         x-init="moveButton();">
        <button type="button"
                title="<?= $escaper->escapeHtmlAttr($buttonText); ?>"
                class="btn btn-primary catalog-product-pos-button <?= $block->getAttributeCodeClass(); ?> <?= $block->getAttributeValueClass(); ?>"
                id="product-button-pos"
                onclick="window.location.href = '<?= $block->getButtonUrl(); ?>';">
            <span class="hidden sm:block md:hidden lg:block">
                <?= $buttonText; ?>
            </span>
        </button>
        <?= $block->getChildHtml(); ?>
    </div>
<?php endif; ?>
