<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogProductPOS\Block\Attribute;

/** @var Attribute $block */
?>

<?php if ($block->getAttributeCode()): ?>
    <div class="catalog-product-pos">
        <div class="catalog-product-pos-attribute <?= $block->getAttributeCodeClass(); ?>">
        </div>
    </div>
    <script id="catalog-product-pos-template" type="text/x-handlebars">
        <div class="catalog-product-pos-attribute-value {{attributeValueClass}}">{{attributeValue}}</div>
    </script>
<?php endif; ?>
